name: Postman Collection Workflow Test

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: 30 02 * * * # 8 am IST
    - cron: 30 13 * * * # 7pm IST


jobs:
  run-new-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v6-beta

    - name: Install Nodejs
      uses: actions/setup-node@v6.0.0
      with:
        node-version: '22'

    - name: Install newman and html extra report
      run: |
            npm install -g newman
            npm install -g newman-reporter-htmlextra

    - name: Run Collection
      run: |
            newman run 'Inwarranty-flow Collection.postman_collection.json' \
            -e QA.postman_environment.json \
            -d testData.csv \
            -r cli,htmlextra

    - name: Newman Reports
      if: always()
      uses: actions/upload-artifact@v5.0.0
      with:
        name: newman html report
        path: newman/*.html
     
    
  
  
